[workspace]
resolver = "2"
members = [
    "mercurio-cli",
    "mercurio-client",
    "mercurio-core",
    "mercurio-packets",
    "mercurio-server",
    "mercurio-storage",
]

[profile.release]
debug = true  # Enable debug symbols for profiling
