[package]
name = "mercurio-core"
version = "0.1.0"
edition = "2021"
description = "Core types and traits for the Mercurio MQTT implementation"
license = "MIT OR Apache-2.0"

[features]
default = ["std"]
std = []

[dependencies]
bytes = { version = "1.3.0", default-features = false }
